language: php
php:
  - 7.1
  - 7.2
matrix:
  include:
    - php: 7.1
      env: dependencies=lowest
    - php: 7.1
      env: dependencies=highest
    - php: 7.2
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=highest
before_script:
  - composer self-update
  - mkdir -p build/log
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
script:
  - make check
after_script:
  - php bin/coveralls -v
